/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#0F4C81',
        'secondary': '#2563EB',
        'accent': '#38BDF8',
        'background': '#F8FAFC',
        'surface': '#FFFFFF',
        'on-background': '#0F172A',
        'on-surface': '#0F172A',
        'on-surface-variant': '#64748B',
        'outline-variant': '#E2E8F0',
        'outline': '#64748B',
        'success': '#22C55E',
        'warning': '#F59E0B',
        'error': '#EF4444',
        // Preserve dim and fixed variants for backwards compatibility
        'surface-dim': '#F8FAFC',
        'primary-fixed-dim': '#93C5FD',
        'surface-container-high': '#F1F5F9',
        'on-tertiary-fixed': '#0F172A',
        'on-primary-fixed-variant': '#0F4C81',
        'primary-container': '#1E3A8A',
        'on-secondary': '#ffffff',
        'surface-variant': '#F1F5F9',
        'on-secondary-container': '#0F172A',
        'on-primary-container': '#ffffff',
        'tertiary': '#2563EB',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#64748B',
        'inverse-on-surface': '#F8FAFC',
        'on-secondary-fixed': '#0F172A',
        'tertiary-container': '#38BDF8',
        'surface-container-low': '#F8FAFC',
        'secondary-container': '#F1F5F9',
        'error-container': '#FEE2E2',
        'on-tertiary-container': '#ffffff',
        'on-primary-fixed': '#0F4C81',
        'surface-container-highest': '#E2E8F0',
        'on-error': '#ffffff',
        'tertiary-fixed': '#F8FAFC',
        'inverse-primary': '#93C5FD',
        'primary-fixed': '#EFF6FF',
        'secondary-fixed-dim': '#CBD5E1',
        'tertiary-fixed-dim': '#E2E8F0',
        'on-secondary-fixed-variant': '#64748B',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#F1F5F9',
        'surface-tint': '#0F4C81',
        'surface-bright': '#F8FAFC',
        'on-error-container': '#EF4444',
        'inverse-surface': '#0F172A',
        'secondary-fixed': '#E2E8F0',
      },
      fontFamily: {
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
        'price-display': ['22px', { lineHeight: '1.1', fontWeight: '800' }],
      },
      spacing: {
        'container-max': '1280px',
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'base': '8px',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
    },
  },
  plugins: [],
};
